repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            .*\.bib|
            \.cspell\.json
          )$
      - id: mixed-line-ending
      - id: name-tests-test
        name: Tests should start with test_
        args: ["--django"]
      - id: trailing-whitespace

  - repo: https://github.com/ComPWA/repo-maintenance
    rev: 0.0.128
    hooks:
      - id: check-dev-files
        args:
          - --pin-requirements=biweekly
      - id: fix-nbformat-version
      - id: format-setup-cfg
      - id: set-nb-cells
        args:
          - --add-install-cell
          - --additional-packages=IPython
          - --extras-require=doc,jax,viz

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.0.0
    hooks:
      - id: cspell

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        exclude: >
          (?x)^(
            .*\.py
          )$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-black
        additional_dependencies:
          - black>=22.1.0
      - id: nbqa-flake8
        args: ["--extend-ignore=E402,F821"]
      - id: nbqa-isort
        args: [--nbqa-mutate]
      - id: nbqa-pyupgrade
        args:
          - --py36-plus

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        args:
          - --extra-keys
          - |
            cell.metadata.code_folding
            cell.metadata.id
            metadata.celltoolbar
            metadata.colab.name
            metadata.colab.provenance
            metadata.interpreter
            metadata.notify_time
            metadata.toc
            metadata.toc-autonumbering
            metadata.toc-showcode
            metadata.toc-showmarkdowntxt
            metadata.toc-showtags
            metadata.varInspector

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/mirrors-pyright
    rev: v1.1.252
    hooks:
      - id: pyright

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus

  # The following tools have to be install locally, because they can also be
  # used by code editors (e.g. linting and format-on-save).

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types:
          - python

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types:
          - python

      - id: isort
        name: isort
        entry: isort
        language: system
        types:
          - python

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        require_serial: true
        types:
          - python

      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types:
          - python

      - id: pylint
        name: pylint
        entry: pylint
        args:
          - --rcfile=.pylintrc
          - --score=no
        language: system
        require_serial: true
        types:
          - python
