version: 2

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
  jobs:
    post_install:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - python -m pip install 'uv>=0.2.0'
      - python -m uv pip install -c .constraints/py3.10.txt -e .[doc]
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - |-
        /home/docs/.cargo/bin/uv pip install --system -c .constraints/py3.10.txt -e .[doc]
