language: python
os: linux
dist: bionic
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install .
script:
  - cd tests
  - CUDA_VISIBLE_DEVICES="" pytest
