language: python
os: linux
dist: bionic

branches:
  only:
    - master
    - /\d+\.\d+.*/
  except:
    - gh-pages

install:
  - pip3 install .[test]

script:
  - pytest --cov=tensorwaves

jobs:
  include:
    - name: "Build and test documentation"
      python: 3.7
      install:
        - sudo apt-get -y install pandoc
        - pip3 install .[doc]
      script:
        - cd doc
        - make linkcheck
        - NBSPHINX_EXECUTE='' make html

    - name: "Style checks"
      python: 3.6
      install:
        - npm install -g cspell
        - pip3 install .[dev]
      script:
        - tox -e sty
        - cspell $(git ls-files)

    - name: "Python 3.6 on Ubuntu 18.04"
      python: 3.6

    - name: "Python 3.7 on Ubuntu 18.04 + CodeCov"
      python: 3.7
      after_success:
        - pip3 install codecov
        - codecov

    - name: "Python 3.7 on macOS (xcode11.2)"
      os: osx
      osx_image: xcode11.2
      language: shell

    - name: "Deploy PyPI package"
      install: echo "Skipping install stage"
      script: echo "Skipping script stage"
      deploy:
        edge: true
        provider: pypi
        on:
          tags: true
        distributions: sdist
        skip_existing: false
        username: __token__
        password:
          secure: "HNhEQB0wTyYcAKz6+m/4P3SQH74R69c/A9V+4H/FKwXJDK2kLIFBnetVT7DAWOoG8ombsMDhnMc+bLxsi053Y1dxsEpdQFBzZV28Rmi2JstDhXe9u2diYs8FdtXYwOZQTq0AH2ntEKSnTxEGh5twm84VUcaIBpk0gUHA89nW8CXT/TQ0BrnGLCwQJDNvVdjMrlLckkZde6Vw2oZOhKt3l1FKP7rdkA+/G4g5guK2mPlgBXzDZxhimJvB4hQRr5jlCV3fmnlUQbL0VntaspvDwnwizIneb/2o7vYco0ZiL18uAARjJQ+r130t3gJq0raLCngsgVjrzitldpPRl9W5xSMP+hmTyUNZjQNpr+421uWN+jvD1cZmcl+Fe9s/nk/6Lip/C/2G/mtGrOM9+mt8E+XejgZjF6d9f1O0gSHszHS037hRDQ7ikZLbGEL1kXHEwvku8W50j6fom8Bmwk0yKwnbjDt/DMNzZy6aHaRTEOi0uExkW2OxsWAMPbGxZ8rAAhVbNgEJ1KXFhC0bPioj85Wy2w7KJJVL3eSdz60FZYtPrslfSj3wpaS/Zd+FSLKbmDwTRz8WY/7BaHQvdgTGciLAT+5bxbPtkOuw4sai/1z2aZLwEPpNnbBaMY0GVWJSiIHHy+VpvFHj2t00toBY4ORLTLyJqv5Ucdwcni0Yc6g="
