language: python
os: linux
dist: bionic

before_install:
  - pip3 install --upgrade pip

install:
  - pip3 install -r requirements.txt
  - pip3 install .

before_script:
  - pip3 install -r tests/requirements.txt

script:
  - cd tests
  - pytest

jobs:
  include:
    - name: "Build and test documentation"
      python: 3.7
      before_script:
        - pip3 install -r doc/requirements.txt
      script:
        - cd doc
        - make linkcheck
        - make html
    - name: "Python 3.5 on Ubuntu 18.04"
      dist: bionic
      python: 3.5
    - name: "Python 3.6 on Ubuntu 18.04"
      python: 3.6
    - name: "Python 3.7 on Ubuntu 18.04"
      python: 3.7
