language: python
os: linux
dist: bionic

branches:
  only:
    - master
    - /\d+\.\d+.*/
  except:
    - gh-pages

before_install:
  - pip3 install --upgrade pip

install:
  - pip3 install -r requirements.txt
  - pip3 install .

before_script:
  - pip3 install -r tests/requirements.txt

script:
  - cd tests
  - pytest

jobs:
  include:
    - name: "Build and test documentation"
      python: 3.7
      before_script:
        - sudo apt-get -y install pandoc
        - pip3 install -r doc/requirements.txt
      script:
        - cd doc
        - make linkcheck
        - NBSPHINX_EXECUTE='' make html

    - name: "Style checks"
      python: 3.6
      script:
        - pip3 install -r requirements-dev.txt
        - black . --check
        - mypy . --config-file tox.ini
        - pre-commit run flake8 -a
        - pre-commit run pylint -a
        - pydocstyle

    - name: "Python 3.6 on Ubuntu 18.04"
      python: 3.6

    - name: "Python 3.7 on Ubuntu 18.04 + CodeCov"
      python: 3.7
      after_success:
        - pip3 install codecov
        - codecov

    - name: "Python 3.7 on macOS (xcode11.2)"
      os: osx
      osx_image: xcode11.2
      language: shell

    - name: "Deploy PyPI package"
      install: echo "Skipping install stage"
      script: echo "Skipping script stage"
      before_script: echo "Skipping before_script stage"
      deploy:
        edge: true
        provider: pypi
        on:
          tags: true
        distributions: sdist
        skip_existing: false
        username: __token__
        password:
          secure: "HNhEQB0wTyYcAKz6+m/4P3SQH74R69c/A9V+4H/FKwXJDK2kLIFBnetVT7DAWOoG8ombsMDhnMc+bLxsi053Y1dxsEpdQFBzZV28Rmi2JstDhXe9u2diYs8FdtXYwOZQTq0AH2ntEKSnTxEGh5twm84VUcaIBpk0gUHA89nW8CXT/TQ0BrnGLCwQJDNvVdjMrlLckkZde6Vw2oZOhKt3l1FKP7rdkA+/G4g5guK2mPlgBXzDZxhimJvB4hQRr5jlCV3fmnlUQbL0VntaspvDwnwizIneb/2o7vYco0ZiL18uAARjJQ+r130t3gJq0raLCngsgVjrzitldpPRl9W5xSMP+hmTyUNZjQNpr+421uWN+jvD1cZmcl+Fe9s/nk/6Lip/C/2G/mtGrOM9+mt8E+XejgZjF6d9f1O0gSHszHS037hRDQ7ikZLbGEL1kXHEwvku8W50j6fom8Bmwk0yKwnbjDt/DMNzZy6aHaRTEOi0uExkW2OxsWAMPbGxZ8rAAhVbNgEJ1KXFhC0bPioj85Wy2w7KJJVL3eSdz60FZYtPrslfSj3wpaS/Zd+FSLKbmDwTRz8WY/7BaHQvdgTGciLAT+5bxbPtkOuw4sai/1z2aZLwEPpNnbBaMY0GVWJSiIHHy+VpvFHj2t00toBY4ORLTLyJqv5Ucdwcni0Yc6g="
