# cspell:ignore CUDA

name: CI for epics

on:
  pull_request:
    branches:
      - epic/*

jobs:
  pytest:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs/${{ matrix.python-version }}/requirements-test.txt
          pip install .
      - name: Test with pytest
        env:
          CUDA_VISIBLE_DEVICES: "-1"
        run: pytest -n auto

  documentation:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs/3.7/requirements-doc.txt
          pip install tensorflow-cpu
          pip install .
          sudo apt-get -y install pandoc
      - name: Build documentation
        working-directory: docs
        env:
          CUDA_VISIBLE_DEVICES: "-1"
        run: make html
      - name: Test doctests in docstrings
        working-directory: docs
        run: make ignore-warnings=1 doctest

  style:
    name: Style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs/3.7/requirements-sty.txt
          pip install .
      - name: Perform style checks
        run: pre-commit run -a
